/**
 * Barth Meta launch: upload video, generate caption with Claude, create campaign with $50/day budget, stream status.
 */

import { loadAllClients, createClaudeClient, type ClientConfig } from "core";
import { join } from "node:path";
import { parseStructuredAdCopy } from "./adCopyParse.js";
import { getMetaLaunchIssue } from "../launchReadiness.js";

const GRAPH_API_VERSION = "v21.0";
const GRAPH_BASE = `https://graph.facebook.com/${GRAPH_API_VERSION}`;
const DAILY_BUDGET_CENTS = 5000; // $50/day

const META_TITLE_MAX = 255;
const META_MESSAGE_MAX = 2000;
/** ~3 min — Meta must finish encoding before it exposes a preview frame from your video. */
const THUMB_POLL_ATTEMPTS = 90;
const THUMB_POLL_MS = 2000;

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function extractPictureUrl(picture: unknown): string | null {
  if (typeof picture === "string" && picture.startsWith("http")) return picture;
  if (picture && typeof picture === "object" && "data" in picture) {
    const d = (picture as { data?: { url?: string } }).data;
    if (d?.url?.startsWith("http")) return d.url;
  }
  return null;
}

async function uploadAdImageBase64(
  accountId: string,
  accessToken: string,
  base64: string,
  name: string
): Promise<string> {
  const thumbForm = new FormData();
  thumbForm.append("access_token", accessToken);
  thumbForm.append("bytes", base64);
  thumbForm.append("name", name);
  const thumbRes = await fetch(`${GRAPH_BASE}/act_${accountId}/adimages`, { method: "POST", body: thumbForm });
  const thumbData = (await parseJsonRes(thumbRes)) as { images?: Record<string, { hash?: string }>; error?: { message: string } };
  if (!thumbRes.ok || thumbData.error) {
    throw new Error(thumbData.error?.message ?? `adimages HTTP ${thumbRes.status}`);
  }
  const firstImage = thumbData.images && Object.values(thumbData.images)[0];
  const hash = firstImage?.hash;
  if (!hash) throw new Error("No image_hash from adimages upload");
  return hash;
}

async function fetchImageAsBase64(imageUrl: string, accessToken: string): Promise<{ base64: string; name: string }> {
  let url = imageUrl;
  if (!url.includes("access_token=")) {
    url += `${url.includes("?") ? "&" : "?"}access_token=${encodeURIComponent(accessToken)}`;
  }
  const imgRes = await fetch(url);
  if (!imgRes.ok) {
    throw new Error(`Thumbnail image fetch HTTP ${imgRes.status}`);
  }
  const buf = Buffer.from(await imgRes.arrayBuffer());
  const ct = imgRes.headers.get("content-type") ?? "";
  const ext = ct.includes("png") ? "png" : ct.includes("webp") ? "webp" : "jpg";
  return { base64: buf.toString("base64"), name: `video-thumb.${ext}` };
}

/** FB often requires access_token on thumbnail URLs for authenticated fetches / creative. */
function ensureAccessTokenOnUrl(uri: string, accessToken: string): string {
  if (uri.includes("access_token=")) return uri;
  const sep = uri.includes("?") ? "&" : "?";
  return `${uri}${sep}access_token=${encodeURIComponent(accessToken)}`;
}

/**
 * Wait until Meta exposes a preview URI for this advideo.
 * That frame is generated by Meta from **your uploaded video** — not a separate creative you pick.
 * Marketing API still requires `image_url` or `image_hash` next to `video_id` (video-only creatives are not supported).
 */
async function waitForMetaVideoPreviewUri(
  videoId: string,
  accessToken: string,
  onStatus: (message: string) => void
): Promise<string> {
  const fields = encodeURIComponent("thumbnails{uri,is_preferred},picture,status");
  onStatus(
    "Barth: Waiting for Meta to finish encoding your video and generate a preview frame (required for every video ad — still only your video file).",
  );

  for (let attempt = 0; attempt < THUMB_POLL_ATTEMPTS; attempt++) {
    const infoUrl = `${GRAPH_BASE}/${videoId}?fields=${fields}&access_token=${encodeURIComponent(accessToken)}`;
    const res = await fetch(infoUrl);
    let data: {
      thumbnails?: { data?: Array<{ uri?: string; is_preferred?: boolean }> };
      picture?: unknown;
      status?: { video_status?: string };
      error?: { message?: string };
    };
    try {
      data = (await parseJsonRes(res)) as typeof data;
    } catch {
      await sleep(THUMB_POLL_MS);
      continue;
    }

    if (!res.ok && data.error) {
      onStatus(`Barth: Video status API warning — ${data.error.message}`);
    }

    const thumbs = data.thumbnails?.data ?? [];
    const pick =
      thumbs.find((t) => t.is_preferred && t.uri) ?? thumbs.find((t) => t.uri) ?? null;
    const thumbUri = pick?.uri ?? extractPictureUrl(data.picture);

    if (thumbUri) {
      onStatus(`Barth: Preview frame from your video is ready (${attempt + 1}/${THUMB_POLL_ATTEMPTS} polls).`);
      return thumbUri;
    }

    const vs = data.status?.video_status;
    if (vs === "error" || vs === "failed") {
      throw new Error(
        "Meta reported an error while processing your video. Re-encode the file or try a different format, then launch again.",
      );
    }

    if (attempt > 0 && attempt % 15 === 0) {
      onStatus(`Barth: Still encoding… (${attempt}/${THUMB_POLL_ATTEMPTS} checks)`);
    }

    await sleep(THUMB_POLL_MS);
  }

  throw new Error(
    "Meta has not finished processing your video yet (no preview frame). Wait 2–3 minutes and run Barth again. Barth only uploads your video; Meta generates the preview after encoding.",
  );
}

export interface BarthMetaLaunchOptions {
  projectRoot: string;
  videoBuffer: Buffer;
  videoFileName: string;
  clientIds: string[];
  brief?: string;
  onStatus: (message: string) => void;
}

function validateMetaClient(client: ClientConfig): { ready?: ClientConfig & { metaAccountId: string; metaAccessToken: string; metaPageId: string }; error?: string } {
  const issue = getMetaLaunchIssue(client);
  if (issue) return { error: issue };
  return {
    ready: client as ClientConfig & { metaAccountId: string; metaAccessToken: string; metaPageId: string },
  };
}

function getMetaAppAccessToken(): string | null {
  const appId = process.env.META_APP_ID?.trim();
  const appSecret = process.env.META_APP_SECRET?.trim();
  if (!appId || !appSecret) return null;
  return `${appId}|${appSecret}`;
}

async function assertMetaTokenValid(metaAccessToken: string): Promise<void> {
  const appAccessToken = getMetaAppAccessToken();
  if (!appAccessToken) return;

  const debugUrl = new URL(`${GRAPH_BASE}/debug_token`);
  debugUrl.searchParams.set("input_token", metaAccessToken);
  debugUrl.searchParams.set("access_token", appAccessToken);

  const res = await fetch(debugUrl.toString());
  const data = (await parseJsonRes(res)) as {
    data?: { is_valid?: boolean };
    error?: { message?: string };
  };
  if (!res.ok || data.error) {
    throw new Error(data.error?.message ?? `Meta token debug HTTP ${res.status}`);
  }
  if (!data.data?.is_valid) {
    throw new Error(
      "Meta token invalid or revoked. Regenerate it: Graph API Explorer (developers.facebook.com/tools/explorer) → select app → Generate Access Token → Extend to long-lived. Or use a System User token (see CREDENTIALS.md). Then update metaAccessToken in config/clients/<client>.json."
    );
  }
}

function normAccountId(id: string): string {
  return id.replace(/^act_/, "");
}

async function parseJsonRes(res: Response): Promise<unknown> {
  let text: string;
  try {
    text = await res.text();
  } catch (e) {
    const errMsg = e instanceof Error ? e.message : String(e);
    throw new Error(`Failed to read response body (${res.status}): ${errMsg}`);
  }
  try {
    return JSON.parse(text);
  } catch {
    const snippet = text.length > 120 ? text.slice(0, 120) + "…" : text;
    throw new Error(`Server returned non-JSON (${res.status}): ${snippet}`);
  }
}

export async function runBarthMetaLaunch(options: BarthMetaLaunchOptions): Promise<void> {
  const { projectRoot, videoBuffer, videoFileName, clientIds, brief, onStatus } = options;
  const clientsDir = join(projectRoot, "config", "clients");

  const { clients, errors } = await loadAllClients({ clientsDir });
  if (errors.length > 0) {
    onStatus(`Barth: Config warnings: ${errors.map((e) => e.file).join(", ")}`);
  }

  const metaClients = clients.filter((c) => clientIds.includes(c.clientName));
  if (metaClients.length === 0) {
    onStatus("Barth: No valid Meta clients selected.");
    return;
  }

  const claude = createClaudeClient();
  const dateStr = new Date().toISOString().slice(0, 10);

  const defaultTargeting = { geo_locations: { countries: ["US"] as string[] } };

  for (const client of metaClients) {
    const validation = validateMetaClient(client);
    if (!validation.ready) {
      onStatus(`Barth: Skipping ${client.clientName} — ${validation.error}`);
      continue;
    }

    const { clientName, metaAccountId, metaAccessToken, metaPageId } = validation.ready;
    const metaWebsiteUrl = validation.ready.metaWebsiteUrl?.trim();
    const metaTargeting = validation.ready.metaTargeting;
    const accountId = normAccountId(metaAccountId);

    const targeting =
      metaTargeting?.geo_locations &&
      (metaTargeting.geo_locations.countries?.length || metaTargeting.geo_locations.custom_locations?.length)
        ? {
            geo_locations: {
              ...(metaTargeting.geo_locations.countries?.length
                ? { countries: metaTargeting.geo_locations.countries }
                : {}),
              ...(metaTargeting.geo_locations.custom_locations?.length
                ? {
                    custom_locations: metaTargeting.geo_locations.custom_locations.map((loc) => ({
                      latitude: loc.latitude,
                      longitude: loc.longitude,
                      radius: loc.radius ?? 10,
                      distance_unit: loc.distance_unit ?? "mile",
                    })),
                  }
                : {}),
            },
          }
        : defaultTargeting;
    const gl = targeting.geo_locations as { countries?: string[]; custom_locations?: unknown[] };
    if (gl.custom_locations?.length && !gl.countries?.length) {
      gl.countries = ["US"];
    }

    try {
      onStatus(`Barth: Starting launch for ${clientName}…`);
      await assertMetaTokenValid(metaAccessToken);

      // 1) Upload video to ad account
      const form = new FormData();
      form.append("access_token", metaAccessToken);
      const blob = new Blob([videoBuffer], { type: "video/mp4" });
      form.append("source", blob, videoFileName);

      const uploadUrl = `${GRAPH_BASE}/act_${accountId}/advideos`;
      const uploadRes = await fetch(uploadUrl, { method: "POST", body: form });
      const uploadData = (await parseJsonRes(uploadRes)) as { id?: string; error?: { message: string } };
      if (!uploadRes.ok || uploadData.error) {
        throw new Error(uploadData.error?.message ?? `Upload HTTP ${uploadRes.status}`);
      }
      const videoId = uploadData.id;
      if (!videoId) throw new Error("No video id returned");
      const uploadedVideoId = videoId;
      onStatus(`Barth: Uploaded video for ${clientName} (${uploadedVideoId}).`);

      // 1b) Meta-generated preview URI from your video (parallel with copy). No separate “random” image.
      const context = brief?.trim()
        ? `${clientName}. Brief: ${brief}`
        : clientName;
      const copyPromise = claude.generateCopy({
        context,
        tone: "short, CTA-focused",
        formatInstructions: `Return a single JSON object only (no markdown, no **Headline:** labels, no code fences). Keys: "headline" (short hook, max ~40 characters) and "primary_text" (body copy, 1–3 sentences). Example: {"headline":"BOGO 50% off this week","primary_text":"Don't wait — buy one, get one 50% off at Sessco."}`,
      });
      const [previewUri, caption] = await Promise.all([
        waitForMetaVideoPreviewUri(videoId, metaAccessToken, onStatus),
        copyPromise,
      ]);
      const parsed = parseStructuredAdCopy(caption || "");
      const headline = parsed.headline.slice(0, META_TITLE_MAX);
      const message = parsed.primaryText.slice(0, META_MESSAGE_MAX);
      onStatus(`Barth: Generated caption for ${clientName}.`);

      // 3) Create campaign with Advantage campaign budget ($50/day at campaign level so we don't need is_adset_budget_sharing_enabled on ad set)
      const campaignName = `Barth – ${clientName} – ${dateStr}`;
      const campaignRes = await fetch(`${GRAPH_BASE}/act_${accountId}/campaigns?access_token=${encodeURIComponent(metaAccessToken)}`, {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: new URLSearchParams({
          name: campaignName,
          objective: "OUTCOME_ENGAGEMENT",
          status: "ACTIVE",
          daily_budget: String(DAILY_BUDGET_CENTS),
          bid_strategy: "LOWEST_COST_WITHOUT_CAP",
          special_ad_categories: "NONE",
        }).toString(),
      });
      const campaignData = (await parseJsonRes(campaignRes)) as { id?: string; error?: { message: string; error_user_msg?: string } };
      if (!campaignRes.ok || campaignData.error) {
        const errMsg = campaignData.error?.error_user_msg ?? campaignData.error?.message ?? `Campaign HTTP ${campaignRes.status}`;
        throw new Error(errMsg);
      }
      const campaignId = campaignData.id;
      if (!campaignId) throw new Error("No campaign id returned");
      onStatus(`Barth: Created campaign for ${clientName} (${campaignId}).`);

      // 4) Create ad set (OUTCOME_ENGAGEMENT requires destination_type + matching optimization_goal; ON_POST allows POST_ENGAGEMENT)
      const adSetName = `Barth – ${clientName} – ad set – ${dateStr}`;
      const adSetBody = new URLSearchParams({
        name: adSetName,
        campaign_id: campaignId,
        billing_event: "IMPRESSIONS",
        optimization_goal: "POST_ENGAGEMENT",
        destination_type: "ON_POST",
        promoted_object: JSON.stringify({ page_id: metaPageId }),
        targeting: JSON.stringify(targeting),
        status: "ACTIVE",
      });
      const adSetRes = await fetch(`${GRAPH_BASE}/act_${accountId}/adsets?access_token=${encodeURIComponent(metaAccessToken)}`, {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: adSetBody.toString(),
      });
      const adSetData = (await parseJsonRes(adSetRes)) as { id?: string; error?: { message: string; error_user_msg?: string } };
      if (!adSetRes.ok || adSetData.error) {
        const errMsg = adSetData.error?.error_user_msg ?? adSetData.error?.message ?? `Ad set HTTP ${adSetRes.status}`;
        throw new Error(errMsg);
      }
      const adSetId = adSetData.id;
      if (!adSetId) throw new Error("No ad set id returned");
      onStatus(`Barth: Created ad set for ${clientName} ($${DAILY_BUDGET_CENTS / 100}/day).`);

      // 5) Video ad creative. Meta requires image_url OR image_hash alongside video_id (same video; preview is a frame they generated).
      const creativeName = `Barth – ${clientName} – creative – ${dateStr}`;
      const previewImageUrl = ensureAccessTokenOnUrl(previewUri, metaAccessToken);

      type VideoDataPayload = {
        video_id: string;
        message: string;
        title?: string;
        image_url?: string;
        image_hash?: string;
        call_to_action?: {
          type: string;
          value: { link: string };
        };
      };

      function buildVideoData(preview: { image_url: string } | { image_hash: string }): VideoDataPayload {
        const base: VideoDataPayload = {
          video_id: uploadedVideoId,
          message,
          ...("image_url" in preview ? { image_url: preview.image_url } : { image_hash: preview.image_hash }),
        };
        if (headline.trim()) base.title = headline.trim();
        if (metaWebsiteUrl) {
          base.call_to_action = {
            type: "LEARN_MORE",
            value: { link: metaWebsiteUrl },
          };
        }
        return base;
      }

      let videoData = buildVideoData({ image_url: previewImageUrl });
      let creativeRes = await fetch(`${GRAPH_BASE}/act_${accountId}/adcreatives?access_token=${encodeURIComponent(metaAccessToken)}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: creativeName,
          object_story_spec: {
            page_id: metaPageId,
            video_data: videoData,
          },
        }),
      });
      let creativeData = (await parseJsonRes(creativeRes)) as { id?: string; error?: { message: string; error_user_msg?: string } };

      if (!creativeRes.ok || creativeData.error) {
        const firstErr = creativeData.error?.error_user_msg ?? creativeData.error?.message ?? `Creative HTTP ${creativeRes.status}`;
        onStatus(
          `Barth: Creative with preview URL only failed (${firstErr}). Saving Meta's frame as image_hash — same video, API requirement for some accounts.`,
        );
        const { base64, name } = await fetchImageAsBase64(previewUri, metaAccessToken);
        const imageHash = await uploadAdImageBase64(accountId, metaAccessToken, base64, name);
        videoData = buildVideoData({ image_hash: imageHash });
        creativeRes = await fetch(`${GRAPH_BASE}/act_${accountId}/adcreatives?access_token=${encodeURIComponent(metaAccessToken)}`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            name: creativeName,
            object_story_spec: {
              page_id: metaPageId,
              video_data: videoData,
            },
          }),
        });
        creativeData = (await parseJsonRes(creativeRes)) as typeof creativeData;
      }

      if (!creativeRes.ok || creativeData.error) {
        const errMsg = creativeData.error?.error_user_msg ?? creativeData.error?.message ?? `Creative HTTP ${creativeRes.status}`;
        throw new Error(errMsg);
      }
      const creativeId = creativeData.id;
      if (!creativeId) throw new Error("No creative id returned");
      onStatus(`Barth: Created creative for ${clientName}.`);

      // 6) Create ad
      const adName = `Barth – ${clientName} – ad – ${dateStr}`;
      const adRes = await fetch(`${GRAPH_BASE}/act_${accountId}/ads?access_token=${encodeURIComponent(metaAccessToken)}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: adName,
          adset_id: adSetId,
          creative: JSON.stringify({ creative_id: creativeId }),
          status: "ACTIVE",
        }),
      });
      const adData = (await parseJsonRes(adRes)) as { id?: string; error?: { message: string; error_user_msg?: string } };
      if (!adRes.ok || adData.error) {
        const errMsg = adData.error?.error_user_msg ?? adData.error?.message ?? `Ad HTTP ${adRes.status}`;
        throw new Error(errMsg);
      }
      onStatus(`Barth: Launch complete for ${clientName}.`);
    } catch (err) {
      let msg = err instanceof Error ? err.message : String(err);
      if (/Unexpected token|is not valid JSON/i.test(msg)) {
        msg = "API returned non-JSON (request may be too large or gateway error).";
      }
      onStatus(`Barth: Error for ${clientName} — ${msg}`);
    }
  }
}
